prometheus:
  image: prom/prometheus:v2.35.0
  container_name: prometheus
  restart: unless-stopped
  command:
    - '--storage.tsdb.retention.time=31d'
    - '--config.file=/etc/prometheus/prometheus.yml'
  volumes:
    - /data/prometheus/config:/etc/prometheus/
    - /data/prometheus/data:/data
  ports:
    - 9090:9090
  links:
    - cadvisor:cadvisor
    - node-exporter:node-exporter
    - esmr5_exporter:esmr5_exporter
    - azrt:azrt

node-exporter:
  image: prom/node-exporter:v1.3.1
  container_name: node_exporter
  restart: unless-stopped
  expose:
    - 9100

cadvisor:
  image: cadvisor:v0.44.1
  container_name: cadvisor
  command:
    - '--raw_cgroup_prefix_whitelist=/docker/ --disable_metrics=hugetlb'
  privileged: true
  restart: unless-stopped
  devices:
    - /dev/kmsg:/dev/kmsg
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  expose:
    - 8080

esmr5_exporter:
  image: esmr5_exporter:1.0
  container_name: esmr5_exporter
  restart: unless-stopped
  devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"
  expose:
    - 8000

azrt:
  image: **
  container_name: azrt
  restart: unless-stopped
  environment:
    - EMAIL=***
    - PASSWORD=***
    - PLANTID=***
  expose:
    - 8080

grafana:
  image: grafana/grafana:7.5.16
  container_name: grafana
  restart: unless-stopped
  user: "$UID:$GID"
  links:
    - prometheus:prometheus
  volumes:
    - /data/grafana:/var/lib/grafana
  environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_USERS_ALLOW_SIGN_UP=false
  ports:
    - 3000:3000
