prometheus:
  image: prom/prometheus:v2.48.1
  container_name: prometheus
  restart: unless-stopped
  command:
    - "--storage.tsdb.retention.time=31d"
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--web.enable-admin-api"
    - "--web.enable-lifecycle"
    - "--storage.tsdb.max-block-duration=2h"
    - "--storage.tsdb.min-block-duration=2h"
  volumes:
    - /data/prometheus/config:/etc/prometheus/
    - /data/prometheus/data:/prometheus/data
  ports:
    - 9090:9090
  links:
    - cadvisor:cadvisor
    - node-exporter:node-exporter
    - esmr5_exporter:esmr5_exporter
    - azrt:azrt

thanos_sidecar:
  image: quay.io/thanos/thanos:v0.33.0
  container_name: thanos_sidecar
  restart: unless-stopped
  command:
    - sidecar
    - --tsdb.path=/prometheus/data
    - --objstore.config-file=/conf/bucket.yml
    - --prometheus.url=http://prometheus:9090
    - --grpc-address=0.0.0.0:10901
  volumes:
    - /data/thanos/config:/conf
    - /data/prometheus/data:/prometheus/data
  links:
    - prometheus:prometheus

thanos_store_gateway:
  image: quay.io/thanos/thanos:v0.33.0
  container_name: thanos_store_gateway
  restart: unless-stopped
  command:
    - store
    - --data-dir=/thanos/data
    - --objstore.config-file=/conf/bucket.yml
    - --grpc-address=0.0.0.0:10901
    - --sync-block-duration=30m
  volumes:
    - /data/thanos/config:/conf
    - /data/thanos/data:/thanos/data

thanos_query:
  image: quay.io/thanos/thanos:v0.33.0
  container_name: thanos_query
  restart: unless-stopped
  command:
    - query
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:9191
    - --store=thanos_sidecar:10901
    - --store=thanos_store_gateway:10901
    - --query.auto-downsampling
  ports:
    - "9191:9191"
  links:
    - thanos_sidecar:thanos_sidecar
    - thanos_store_gateway:thanos_store_gateway

thanos_compactor:
  image: quay.io/thanos/thanos:v0.33.0
  container_name: thanos_compactor
  restart: unless-stopped
  command:
    - compact
    - --data-dir=/thanos/data
    - --objstore.config-file=/conf/bucket.yml
    - --retention.resolution-raw=30d
    - --retention.resolution-5m=120d
    - --retention.resolution-1h=0d
    - --consistency-delay=60m
    - --downsample.concurrency=1
    - --compact.concurrency=1
    - --log.level=debug
    - --web.disable
    - --block-viewer.global.sync-block-interval=60m
    - --block-meta-fetch-concurrency=1
    - --compact.cleanup-interval=0s
    - --compact.progress-interval=0s
    - --wait
    - --wait-interval=8h
  volumes:
    - /data/thanos/config:/conf
    - /data/thanos/compactor:/thanos/data

node-exporter:
  image: prom/node-exporter:v1.7.0
  container_name: node_exporter
  restart: unless-stopped
  expose:
    - 9100

cadvisor:
  image: gcr.io/cadvisor/cadvisor:v0.47.2
  container_name: cadvisor
  command:
    - "--raw_cgroup_prefix_whitelist=/docker/ --disable_metrics=hugetlb"
  privileged: true
  restart: unless-stopped
  devices:
    - /dev/kmsg:/dev/kmsg
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  expose:
    - 8080

esmr5_exporter:
  image: 388874647441.dkr.ecr.eu-central-1.amazonaws.com/esmr5_exporter:2b48fb80ef4602e62bdb639ff65f92e44f48fb3d
  container_name: esmr5_exporter
  restart: unless-stopped
  devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"
  expose:
    - 8000

azrt:
  image: 388874647441.dkr.ecr.eu-central-1.amazonaws.com/azrt:d855d613818aab0876bdbff445049c0c04f66e14
  container_name: azrt
  restart: unless-stopped
  env_file: azrt.env
  expose:
    - 8080

brandweerrooster_client:
  image: 388874647441.dkr.ecr.eu-central-1.amazonaws.com/brandweerrooster_client:d240fb26efe36984e860dbd7600630355bc78b0e
  container_name: brandweerrooster_client
  restart: unless-stopped
  env_file: brandweerrooster_client.env

grafana:
  image: grafana/grafana:10.2.3
  container_name: grafana
  restart: unless-stopped
  user: "$UID:$GID"
  links:
    - prometheus:prometheus
    - thanos_query:thanos_query
  volumes:
    - /data/grafana:/var/lib/grafana
  env_file: grafana.env
  ports:
    - 3000:3000
