prometheus:
  image: prom/prometheus:v2.42.0
  container_name: prometheus
  restart: unless-stopped
  command:
    - '--storage.tsdb.retention.time=31d'
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--web.enable-admin-api'
    - '--web.enable-lifecycle'
    - '--storage.tsdb.max-block-duration=2h'
    - '--storage.tsdb.min-block-duration=2h'
  volumes:
    - /data/prometheus/config:/etc/prometheus/
    - /data/prometheus/data:/prometheus/data
  ports:
    - 9090:9090
  links:
    - cadvisor:cadvisor
    - node-exporter:node-exporter
    - esmr5_exporter:esmr5_exporter
    - azrt:azrt

thanos_sidecar:
  image: quay.io/thanos/thanos:v0.30.2
  container_name: thanos_sidecar
  command:
    - sidecar
    - --tsdb.path=/prometheus/data
    - --objstore.config-file=/conf/bucket.yml
    - --prometheus.url=http://prometheus:9090
    - --grpc-address=0.0.0.0:10901
  volumes:
    - /data/thanos/config:/conf
    - /data/prometheus/data:/prometheus/data
  links:
    - prometheus:prometheus

thanos_store_gateway:
  image: quay.io/thanos/thanos:v0.30.2
  container_name: thanos_store_gateway
  command:
    - store
    - --data-dir=/thanos/data
    - --objstore.config-file=/conf/bucket.yml
    - --grpc-address=0.0.0.0:10901
    - --sync-block-duration=30m
  volumes:
    - /data/thanos/config:/conf
    - /data/thanos/data:/thanos/data

thanos_query:
  image: quay.io/thanos/thanos:v0.30.2
  container_name: thanos_query
  command:
    - query
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:9191
    - --store=thanos_sidecar:10901
    - --store=thanos_store_gateway:10901
  ports:
    - '9191:9191'
  links:
    - thanos_sidecar:thanos_sidecar
    - thanos_store_gateway:thanos_store_gateway

node-exporter:
  image: prom/node-exporter:v1.5.0
  container_name: node_exporter
  restart: unless-stopped
  expose:
    - 9100

cadvisor:
  image: gcr.io/cadvisor/cadvisor:v0.47.0
  container_name: cadvisor
  command:
    - '--raw_cgroup_prefix_whitelist=/docker/ --disable_metrics=hugetlb'
  privileged: true
  restart: unless-stopped
  devices:
    - /dev/kmsg:/dev/kmsg
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  expose:
    - 8080

esmr5_exporter:
  image: 388874647441.dkr.ecr.eu-central-1.amazonaws.com/esmr5_exporter:cf0a956ea47dee58e7126874b286ae261bf99cd1
  container_name: esmr5_exporter
  restart: unless-stopped
  devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"
  expose:
    - 8000

azrt:
  image: 388874647441.dkr.ecr.eu-central-1.amazonaws.com/azrt:d6944481583f6fba0b698226a06d83a57a18332b
  container_name: azrt
  restart: unless-stopped
  env_file: azrt.env
  expose:
    - 8080

brandweerrooster_client:
  image: 388874647441.dkr.ecr.eu-central-1.amazonaws.com/brandweerrooster_client:3cc3abbf926375492b672051ab12d908d1b98d19
  container_name: brandweerrooster_client
  restart: unless-stopped
  env_file: brandweerrooster_client.env

grafana:
  image: grafana/grafana:9.4.3
  container_name: grafana
  restart: unless-stopped
  user: "$UID:$GID"
  links:
    - prometheus:prometheus
    - thanos_query:thanos_query
  volumes:
    - /data/grafana:/var/lib/grafana
  env_file: grafana.env
  ports:
    - 3000:3000
