prometheus:
  image: prom/prometheus:latest
  container_name: prometheus
  restart: unless-stopped
  command: --storage.tsdb.retention.time=15d --config.file=/etc/prometheus/prometheus.yml
  volumes:
    - /data/prometheus/config:/etc/prometheus/
    - /data/prometheus/data:/data
  ports:
    - 9090:9090
  links:
    - cadvisor:cadvisor
    - node-exporter:node-exporter
    - esmr5_exporter:esmr5_exporter
    - azrt:azrt

node-exporter:
  image: prom/node-exporter:latest
  container_name: node_exporter
  restart: unless-stopped
  expose:
    - 9100

cadvisor:
  image: zcube/cadvisor
  container_name: cadvisor
  restart: unless-stopped
  devices:
    - /dev/kmsg
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  expose:
    - 8080

esmr5_exporter:
  image: esmr5_exporter:1.0
  container_name: esmr5_exporter
  restart: unless-stopped
  devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"
  expose:
    - 8000

azrt:
  image: **
  container_name: azrt
  restart: unless-stopped
  environment:
    - EMAIL=***
    - PASSWORD=****
    - PLANTID=***
  expose:
    - 8080

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  restart: unless-stopped
  user: "$UID:$GID"
  links:
    - prometheus:prometheus
  volumes:
    - /data/grafana:/var/lib/grafana
  environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_USERS_ALLOW_SIGN_UP=false
  ports:
    - 3000:3000