name: main

on: [push]

jobs:
  docker-compose-config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Running docker compose config
      run: |
        touch brandweerrooster_client.env
        docker compose -f docker-compose.yml config --no-interpolate

