name: Check up-to-date

on:
  schedule:
    - cron: '34 7 * * 6'
  push:
    branches: [ main ]

jobs:
  dip:
    name: Check if images are up-to-date inside docker-compose file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Run check-up-to-date
        run: ./scripts/check-up-to-date.sh

      - name: Run check-up-to-date-thanos
        run: ./scripts/check-up-to-date-thanos.sh

      - name: Run check-up-to-date-cadvisor
        run: ./scripts/check-up-to-date-cadvisor.sh

      - name: Create Branch & PR
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Changes to commit"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git checkout -b update-docker-image
            git add .
            git commit -m "Update Docker image(s)"
            git push --set-upstream origin update-docker-image
            gh pr create --head update-docker-image --title "Update Docker image(s)" --body "Please review and approve" --reviewer rvanbutselaar
          else
            echo "No changes to commit"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}