name: Check up-to-date

on:
  schedule:
    - cron: '34 7 * * 6'
  push:
    branches: [ main ]

jobs:
  dip:
    name: Check if images are up-to-date inside docker-compose file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Run check-up-to-date
        run: ./check-up-to-date.sh

      - name: Run check-up-to-date-thanos
        run: ./check-up-to-date-thanos.sh

      - name: Run check-up-to-date-cadvisor
        run: ./check-up-to-date-cadvisor.sh

      - name: Create PR
        run:  gh pr create --base main --title "Update Docker image(s)" --body "Please review and approve" --reviewer rvanbutselaar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}