name: Check up-to-date

on:
  schedule:
    - cron: '34 7 * * 6'
  push:
    branches: [ main ]

jobs:
  dip:
    name: Check if images are up-to-date inside docker-compose file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Run check-up-to-date
        run: ./check-up-to-date.sh

      - name: Run check-up-to-date-thanos
        run: ./check-up-to-date-thanos.sh

      - name: Run check-up-to-date-cadvisor
        run: ./check-up-to-date-cadvisor.sh

      - name: Create Branch
        uses: actions/checkout@v3
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b update-docker-image
          git add .
          git commit -m "Update Docker image(s)"
          git push

      - name: Create PR
        run:  gh pr create --head update-docker-image --title "Update Docker image(s)" --body "Please review and approve" --reviewer rvanbutselaar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
