name: Build & Deploy AZRT

on:
  schedule:
    - cron: '34 7 * * 6'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dip:
    name: Check if images are up-to-date inside docker-compose file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run check-up-to-date
        run: ./check-up-to-date.sh
      - name: Run check-up-to-date-thanos
        run: ./check-up-to-date-thanos.sh
