name: main

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Running docker compose config
      run: |
        docker compose -f docker-compose.yml config --no-interpolate

